name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List all files
      run: ls -R  # This step will list all files and directories, helping us debug the path issue

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run: mvn clean install

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .  # Set the context to the root of the repository or wherever the Dockerfile is located
        dockerfile: AngularProject/UserManagement/Dockerfile  # Path to the Dockerfile relative to the context
        image: ${{ secrets.DOCKERHUB_USERNAME }}/prabhu2000/aws-githun-action
        tags: latest
        registry: docker.io
        push: true
        no-cache: true
